FROM node:14

# Install global packages
RUN npm install -g gulp-cli mocha

RUN mkdir -p /usr/src/habitrpg
WORKDIR /usr/src/habitrpg
COPY package*.json ./
RUN npm install
COPY . .

# Start Habitica
RUN npm run postinstall
CMD ["npm", "start"]
